version: 2
jobs:
  build:
    docker:
      - image: shinsukeabe/circleci-serverless-python3:latest
    steps:
      - checkout:
      - run:
        name: deploy serverless functions
        command: sls deploy -v
      - run:
        name: distribute developers assets
        command: sls invoke stepf --name my-assistant-generate-client
    filters:
      branches:
        only: master
